<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HPA.SurveyFlow.Domain\HPA.SurveyFlow.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.*" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.*" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.15.1-beta.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Quartz" Version="1.15.1-beta.1" />
    <PackageReference Include="PuppeteerSharp" Version="21.*" />
    <PackageReference Include="Quartz" Version="3.18.1" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.18.1" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
