FROM node:22-alpine AS dev

WORKDIR /app/src/HPA.SurveyFlow.Web

COPY src/HPA.SurveyFlow.Web/.npmrc src/HPA.SurveyFlow.Web/package.json src/HPA.SurveyFlow.Web/package-lock.json ./
RUN npm install

EXPOSE 4200
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200"]

FROM node:22-alpine AS build

ARG ANGULAR_API_BASE_URL

WORKDIR /app/src/HPA.SurveyFlow.Web

COPY src/HPA.SurveyFlow.Web/.npmrc src/HPA.SurveyFlow.Web/package.json src/HPA.SurveyFlow.Web/package-lock.json ./
RUN npm ci

COPY src/HPA.SurveyFlow.Web/ ./
RUN npm run build

FROM nginx:alpine AS prod

COPY Docker/nginx.web.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/src/HPA.SurveyFlow.Web/dist/hpa-surveyflow-web/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
